services:
  external-resources-api:
    image: external-resources-api:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DEBUG_FLASK=True
      - LOG_LEVEL=debug
      - DEFAULT_NAMESERVERS=8.8.8.8,77.88.8.8
